### PR TITLE
update to ghost 1.17.2

### PR DESCRIPTION
**Pull request by mchikhaoui**

### CODE REVIEW

**Comment by RadoslavGatev** [comment]
Thanks @mchikhaoui!
We are happy to see your contribution! ⭐️  

I know we haven't established a contribution guide yet, so can I ask you to briefly describe what you did here? Like commands executed, files removed, files changed manually.

Have you tested this against a real Azure Web App? Please, see my recent commit: https://github.com/solvsoftware/Ghost-Azure/commit/9f3504e9c0b72693e0f39d50932393ad1390aa4a.

**Comment by mchikhaoui** [comment]
hi @RadoslavGatev 
I just upgraded the ghost branch to 1.17.2 and merge it with the azure branch.
I tested it locally and it worked fine, butI have not tested yet on azure.

**Review by mazhlekov — CHANGES_REQUESTED** [review]
Hi @mchikhaoui,
We highly appreciate your contribution!

However, I see that you missed to update the casper theme and probably some steps that I'm listing below.

We use the Ghost CLI to generate a new project and build it using the version we want. Then we remove the unneeded stuff from the version folder.
Please make sure that the project is properly built(run it once)
./core/built is important for the administration.
./content/themes/casper should be without .git folder
There should be no submodules.

I will try to find a spare time for documenting the process step by step. For now, you can compare with what I did in the "ghost" branch.

**Comment by mchikhaoui** [comment]
ok, i'll do that for next time.
I recommend that you ignore this pull request, and I will do another cleaner with the new version 1.17.3;)

**Comment by mazhlekov** [comment]
There is no need for a new pull request. Check the link below.

https://stackoverflow.com/a/9790530

**Comment by mchikhaoui** [comment]
hi guys,

after verifcation of my pull request, I found that everything is already clean:
casper is up to date (2.1.6) and it does not contain .git folder (I use the prod version and not source code version)

I updated ghost to version 1.17.3 today, and I tested it on azure, it works, you can check it on my blog http://mchikhaoui.net.

**Review by mazhlekov — APPROVED** [review]

**Pull request merged**
